### ISSUE TITLE
Function to check formatting of reppops

### ISSUE THREAD

**Issue by eriqande** [eriqande/gscramble#39]
Write the function and then make sure that it is called when we are using reppops.

Some things to deal with are:

```r
  # ERROR CHECKING (gotta do)
  # Write a function to do a variety of things...
    # is tibble
    # check that reps requested are dense (no missing numbers in there...)
    # etc.
```

**Comment by rmgiglio** [comment]
Finished this function. I did add a section that checks if the columns are of the correct class (based off of RepPop1 and RepPop4). However, I wasn't sure if 'pop' or 'group' had to be a character. For instance, if you had your groups just labelled as 1,2,3,4, would they still need to be coerced to be characters or do the functions that use RepPops not really care what class these are? It seems clear that the index needs to be an integer, so feel free to modify the function to have it check just that column rather than all 3.

**Comment by rmgiglio** [comment]
Function is check_reppops() @eriqande
